Show certificate when there is a hostname mismatch
I am getting a hostname mismatch error for one of three servers in a
pool so I am suspecting that one server has an invalid certificate.

    requests.exceptions.SSLError: hostname '10.10.194.37' doesn't match u'vault.service.trouper'

by itself is not much info to go on. It would be nice to see the server
certificate that was presented.

I found that it was surprisingly difficult to see the server
certificate, so I decided to see if urllib3 could show the certificate.

With this, urllib3 logs an error with the certificate just before raising the
exception:

```
ERROR:requests.packages.urllib3.connection:Certificate did not match expected hostname: 10.10.194.38.
Certificate: {'subjectAltName': (('IP Address', '127.0.0.1'), ('IP Address', '10.10.194.36'), ('IP Address', '10.10.194.37'), ('IP Address', '10.10.194.38')),
'notBefore': u'Mar 17 01:18:27 2016 GMT', 'serialNumber': u'9BFDB58B08E7DCCA', 'notAfter': 'Mar 15 01:18:27 2026 GMT', 'version': 3L,
'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'California'),), (('localityName', u'Palo Alto'),), (('organizationName', u'DevOps'),), (('commonName', u'vault.service.trouper'),)), 'issuer': ((('countryName', u'US'),), (('stateOrProvinceName', u'California'),), (('localityName', u'Palo Alto'),), (('organizationName', u'DevOps'),), (('commonName', u'vault.service.trouper'),))}
```

which allows me to check whether the server is presenting the correct certificate.

I also add the certificate to the exception that is raised so that
client code can inspect it.