Deal with ssl.PROTOCOL_TLSv1 removal from Python built with OpenSSL 4+
https://github.com/python/cpython/commit/3364e7e62fa24d0e19133fb0f90b1c24ef1110c5
removed ssl.PROTOCOL_TLSv1 when python is built with OpenSSL 4+.

We are hitting this error in Fedora (where we already updated OpenSSL):

    ImportError while loading conftest '/builddir/build/BUILD/python-urllib3-2.7.0-build/urllib3-2.7.0/test/conftest.py'.
    test/__init__.py:42: in <module>
        import urllib3.contrib.pyopenssl as pyopenssl
    ../BUILDROOT/usr/lib/python3.15/site-packages/urllib3/contrib/pyopenssl.py:72: in <module>
        ssl.PROTOCOL_TLSv1: OpenSSL.SSL.TLSv1_METHOD,
        ^^^^^^^^^^^^^^^^^^
    E   AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1'. Did you mean '.PROTOCOL_TLS' instead of '.PROTOCOL_TLSv1'?

Used LLM to figure out what to use as a replacement protocol in tests.

Assisted-By: Claude Opus 4.6